# Generated by Django 2.2.10 on 2021-05-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='title',
            field=models.CharField(default='title', max_length=500),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(max_length=5000),
        ),
    ]
