# Generated by Django 2.2.10 on 2021-05-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20210529_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='title',
            field=models.CharField(default='no title', max_length=500),
        ),
    ]
